context("sr")

test_that("sr", {
  bh <- ypr_sr(ypr_population())
  ri <- ypr_sr(ypr_population(BH = 0L))
  expect_is(bh, "list")
  expect_identical(names(bh), c("alpha", "beta", "phi", "phiF", "R0", "R0F"))
  expect_identical(names(ri), names(bh))
  expect_equal(bh$alpha, 6.708921e-06, check.attributes = FALSE)
  expect_equal(bh$beta, bh$alpha, check.attributes = FALSE)
  expect_equal(bh$R0F, 0.1343839, check.attributes = FALSE, tolerance = 1e-07)
  expect_equal(bh$phi, 447165.8, check.attributes = FALSE, tolerance = 1e-07)
  expect_equal(bh$phiF, 172195.6, check.attributes = FALSE, tolerance = 1e-06)
  expect_identical(unname(bh$R0F), bh(bh$R0F * bh$phiF, bh$alpha, bh$beta))
  expect_equal(unname(ri$R0F), ri(ri$R0F * ri$phiF, ri$alpha, ri$beta))
  expect_identical(ri[c("alpha", "phi", "phiF")], bh[c("alpha", "phi", "phiF")])
  expect_equal(ri$beta, 2.468074e-06, check.attributes = FALSE)
  expect_equal(ri$R0F, 0.3395686, check.attributes = FALSE, tolerance = 1e-07)
})
