context("sr")

test_that("sr", {
  bh <- ypr_sr(ypr_population())
  ri <- ypr_sr(ypr_population(BH = 0L))
  expect_is(bh, "numeric")
  expect_identical(names(bh), c("alpha", "beta", "phi", "phiF", "R0F"))
  expect_identical(names(ri), names(bh))
  expect_equal(bh["alpha"], 6.708921e-06, check.attributes = FALSE)
  expect_equal(bh["beta"], 4.472614e-06, check.attributes = FALSE)
  expect_equal(bh["R0F"], 0.2015758, check.attributes = FALSE)
  expect_equal(bh["phi"], 447165.8, check.attributes = FALSE, tolerance = 1e-07)
  expect_equal(bh["phiF"], 172195.6, check.attributes = FALSE, tolerance = 1e-06)
  expect_identical(ri[c("alpha", "phi", "phiF")], bh[c("alpha", "phi", "phiF")])
  expect_equal(ri["beta"], 2.456835e-06, check.attributes = FALSE)
  expect_equal(ri["R0F"], 0.3411221, check.attributes = FALSE, tolerance = 1e-07)
})
