---
title: "{{{ title }}}"
date: "{{{ date }}}"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.width = 4,
  fig.height = 4
)
```

{{{ description }}}
```{r}
library(ypr)
population <- {{{ population }}}
```

```{r}
knitr::kable(ypr_tabulate_parameters(population))
```

```{r}
ypr_plot_schedule(population)
ypr_plot_schedule(population, "Length", "Weight")
ypr_plot_schedule(population, "Weight", "Fecundity")
ypr_plot_schedule(population, "Length", "Spawning")
```

```{r}
ypr_plot_schedule(population, "Length", "Vulnerability")
ypr_plot_schedule(population, "Length", "Retention")
ypr_plot_schedule(population, "Length", "FishingMortality")
ypr_plot_schedule(population, "Length", "NaturalMortality")
```

```{r}
ypr_plot_fish(population, color = "white")
ypr_plot_fish(population, "Length", "Caught")
ypr_plot_fish(population, "Age", "Spawners", color = "white")
ypr_plot_fish(population, "Length", "Spawners")
ypr_plot_biomass(population, color = "white")
ypr_plot_biomass(population, y = "Eggs", color = "white")
```

```{r, fig.width = 6, fig.height = 4}
ypr_plot_sr(population)
knitr::kable(ypr_sr(population))
knitr::kable(ypr_tabulate_sr(population))
```

```{r, fig.width = 6, fig.height = 4}
ypr_plot_yield(population, Ly = {{{ Ly }}}, harvest = {{{ harvest }}}, biomass = {{{ biomass }}})
knitr::kable(ypr_tabulate_yield(population, Ly = {{{ Ly }}}, harvest = {{{ harvest }}}, biomass = {{{ biomass }}}))
```
