chk_parameters <- function(tmax, k, Linf, t0, k2, Linf2, L2, Wb, Ls, Sp, es, tR,
                           Rk, BH, fb, n, nL, Ln, Sm, pi, Lv, Vp, Llo, Lup, rho,
                           Hm, Nc, Wa, fa, Rmax, q) {
  chk_whole_number(tmax)
  chk_range(tmax, c(1, 100))
  chk_number(k)
  chk_range(k, c(0.015, 15))
  chk_number(Linf)
  chk_range(Linf, c(1, 1000))
  chk_number(t0)
  chk_range(t0, c(-10, 10))
  chk_number(k2)
  chk_range(k2, c(0, 15))
  chk_number(Linf2)
  chk_range(Linf2, c(1, 1000))
  chk_number(L2)
  chk_range(L2, c(-100, 1000))
  chk_number(Wb)
  chk_range(Wb, c(2, 4))
  chk_number(Ls)
  chk_range(Ls, c(-100, 1000))
  chk_number(Sp)
  chk_range(Sp, c(0, 1000))
  chk_number(es)
  chk_range(es, c(0.01, 1))
  chk_whole_number(tR)
  chk_range(tR, c(0L, 10L))
  chk_number(Rk)
  chk_range(Rk, c(1, 100))
  chk_whole_number(BH)
  chk_range(BH, c(0L, 1L))
  chk_number(fb)
  chk_range(fb, c(0.5, 2))
  chk_number(n)
  chk_range(n, c(0, 1))
  chk_number(nL)
  chk_range(nL, c(0, 1))
  chk_number(Ln)
  chk_range(Ln, c(-100, 1000))
  chk_number(Sm)
  chk_range(Sm, c(0, 1))
  chk_number(pi)
  chk_range(pi, c(0, 1))
  chk_number(Lv)
  chk_range(Lv, c(-100, 1000))
  chk_number(Vp)
  chk_range(Vp, c(0, 100))
  chk_number(Llo)
  chk_range(Llo, c(0, 1000))
  chk_number(Lup)
  chk_range(Lup, c(0, 1000))
  chk_number(rho)
  chk_range(rho, c(0, 1))
  chk_number(Hm)
  chk_range(Hm, c(0, 1))
  chk_number(Nc)
  chk_range(Nc, c(0, 1))
  chk_number(Wa)
  chk_range(Wa, c(0.001, 0.1))
  chk_number(fa)
  chk_range(fa, c(1e-04, 100))
  chk_number(Rmax)
  chk_range(Rmax, c(1, 1e+06))
  chk_number(q)
  chk_range(q, c(0, 1))
}
