chk_parameters <- function(tmax, k, Linf, t0, Wb, Ls, Sp, es, tR, Rk, BH, fb, M, Mb, Sm, pi, Lv, Vp, Llo, Lup, rho, Hm, Nc, Wa, fa, Rmax, A0, q) {
  chk_s3_class(tmax, "integer")
  chk_scalar(tmax)
  chk_not_any_na(tmax)
  chk_range(tmax, c(1L, 100L))
  chk_s3_class(k, "numeric")
  chk_scalar(k)
  chk_not_any_na(k)
  chk_range(k, c(0.015, 15))
  chk_s3_class(Linf, "numeric")
  chk_scalar(Linf)
  chk_not_any_na(Linf)
  chk_range(Linf, c(1, 1000))
  chk_s3_class(t0, "numeric")
  chk_scalar(t0)
  chk_not_any_na(t0)
  chk_range(t0, c(-10, 10))
  chk_s3_class(Wb, "numeric")
  chk_scalar(Wb)
  chk_not_any_na(Wb)
  chk_range(Wb, c(2, 4))
  chk_s3_class(Ls, "numeric")
  chk_scalar(Ls)
  chk_not_any_na(Ls)
  chk_range(Ls, c(1, 1000))
  chk_s3_class(Sp, "numeric")
  chk_scalar(Sp)
  chk_not_any_na(Sp)
  chk_range(Sp, c(0, 1000))
  chk_s3_class(es, "numeric")
  chk_scalar(es)
  chk_not_any_na(es)
  chk_range(es, c(0.01, 1))
  chk_s3_class(tR, "integer")
  chk_scalar(tR)
  chk_not_any_na(tR)
  chk_range(tR, c(0L, 10L))
  chk_s3_class(Rk, "numeric")
  chk_scalar(Rk)
  chk_not_any_na(Rk)
  chk_range(Rk, c(1, 100))
  chk_s3_class(BH, "integer")
  chk_scalar(BH)
  chk_not_any_na(BH)
  chk_range(BH, c(0L, 1L))
  chk_s3_class(fb, "numeric")
  chk_scalar(fb)
  chk_not_any_na(fb)
  chk_range(fb, c(0.5, 2))
  chk_s3_class(M, "numeric")
  chk_scalar(M)
  chk_not_any_na(M)
  chk_range(M, c(0.01, 100))
  chk_s3_class(Mb, "numeric")
  chk_scalar(Mb)
  chk_not_any_na(Mb)
  chk_range(Mb, c(-1, 1))
  chk_s3_class(Sm, "numeric")
  chk_scalar(Sm)
  chk_not_any_na(Sm)
  chk_range(Sm, c(0, 1))
  chk_s3_class(pi, "numeric")
  chk_scalar(pi)
  chk_not_any_na(pi)
  chk_range(pi, c(0, 1))
  chk_s3_class(Lv, "numeric")
  chk_scalar(Lv)
  chk_not_any_na(Lv)
  chk_range(Lv, c(1, 1000))
  chk_s3_class(Vp, "numeric")
  chk_scalar(Vp)
  chk_not_any_na(Vp)
  chk_range(Vp, c(0, 100))
  chk_s3_class(Llo, "numeric")
  chk_scalar(Llo)
  chk_not_any_na(Llo)
  chk_range(Llo, c(0, 1000))
  chk_s3_class(Lup, "numeric")
  chk_scalar(Lup)
  chk_not_any_na(Lup)
  chk_range(Lup, c(0, 1000))
  chk_s3_class(rho, "numeric")
  chk_scalar(rho)
  chk_not_any_na(rho)
  chk_range(rho, c(0, 1))
  chk_s3_class(Hm, "numeric")
  chk_scalar(Hm)
  chk_not_any_na(Hm)
  chk_range(Hm, c(0, 1))
  chk_s3_class(Nc, "numeric")
  chk_scalar(Nc)
  chk_not_any_na(Nc)
  chk_range(Nc, c(0, 1))
  chk_s3_class(Wa, "numeric")
  chk_scalar(Wa)
  chk_not_any_na(Wa)
  chk_range(Wa, c(0.001, 0.1))
  chk_s3_class(fa, "numeric")
  chk_scalar(fa)
  chk_not_any_na(fa)
  chk_range(fa, c(1e-04, 100))
  chk_s3_class(Rmax, "numeric")
  chk_scalar(Rmax)
  chk_not_any_na(Rmax)
  chk_range(Rmax, c(1, 1e+06))
  chk_s3_class(A0, "numeric")
  chk_scalar(A0)
  chk_not_any_na(A0)
  chk_range(A0, c(0, 1))
  chk_s3_class(q, "numeric")
  chk_scalar(q)
  chk_not_any_na(q)
  chk_range(q, c(0, 1))
}
chk_population <- function(x, x_name = NULL) {
  if(is.null(x_name)) x_name <- deparse_backtick_chk(substitute(x))
  chk_string(x_name, x_name = "x_name")

  chk_s3_class(x, "ypr_population", x_name = x_name)
  chk_named(x, x_name = x_name)
  chk_unique(names(x), x_name = x_name)
  chk_superset(names(x), .parameters$Parameter, x_name = x_name)

  do.call("chk_parameters", x)
  x
}

chk_populations <- function(x, x_name = NULL) {
  if(is.null(x_name)) x_name <- deparse_backtick_chk(substitute(x))

  chk_list(x, x_name = x_name)
  chk_named(x, x_name = x_name)
  chk_unique(names(x), x_name = x_name)

  x_name <- paste("elements of", x_name)

  chk_s3_class(x, "ypr_populations")

  chk_all(x, chk_population, x_name = x_name)

  x
}
